### PR TITLE
CNN in your own data

### PR DESCRIPTION
**Pull request by pepure**
Convolutional Neural Network classifier for Local Classify Images.

### CODE REVIEW

**Comment by Oceania2018** [comment]
@pepure Appreciate for your contribution. Can you also upload a screenshot for the running result?

**Comment by pepure** [comment]
some problem in opencvsharp4 :
image
I use EmguCv.dll , these code following is OK:
image
but I use Opencvsharp4 by NuGet , some errors occur:
image

**Comment by pepure** [comment]
bug fiix , running ok now~
image
image
image

**Comment by Oceania2018** [comment]
@pepure Looks awesome, last piece, could you please add your example link in the ReadMe?

image

**Comment by pepure** [comment]
ok, link add :
image

**Comment by Oceania2018** [comment]
Thanks, your example will benefit many developers.

**Comment by itzukah** [comment]
Amazing!! Thanks for the update..

**Pull request merged**
